### ISSUE TITLE
Texte und Inhalte vor Relaunch überarbeiten

### ISSUE THREAD

**Issue by jessor** [freifunk-fulda/fulda.freifunk.net#10]
@mfuhrmann hat angeregt, die Texte alle einmal zu überarbeiten. Zu diesem Zweck habe ich ein Dokument mit den Texten, wie sie aktuell auf der Stagingseite stehen, angelegt.

Man kann direkt editieren oder Kommentare einfügen. Formatierung ist an der Stelle irrelevant.

Texte: https://docs.google.com/a/enthusiasm.cc/document/d/1N2J6rP726bdmD4bFdVDzc_QLobvhGERE53M2Dwsky6s/edit?usp=sharing

**Comment by mfuhrmann** [comment]
Ich bringe den Stein mal ins Rollen. Ich habe die "Was ist Freifunk" Seite stark überarbeitet.

**Comment by jessor** [comment]
Vielen Dank :)
