### ISSUE TITLE
Icons fehlen auf Startseite

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/fulda.freifunk.net#17]
Für die Punkte:
- Anonym & Rechtssicher
- Unzensiert

**Comment by jessor** [comment]
Auf welchem System/Browser?

**Comment by mfuhrmann** [comment]
Ubuntu 15.04 / Firefox

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Daniel Kay notifications@github.com 
Datum: 13.11.2015  17:14  (GMT+01:00) 
An: "freifunk-fulda/fulda.freifunk.net" fulda.freifunk.net@noreply.github.com 
Cc: Marcel Fuhrmann fuhrmann@n3rd.org 
Betreff: Re: [fulda.freifunk.net] Icons fehlen auf Startseite (#17) 

Auf welchem System/Browser?
