### ISSUE TITLE
Mesh Karte in neuem Fenster öffnen

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/fulda.freifunk.net#18]
Also mich kann das auf die Palme bringen...
Keine Ahnung wie ihr das seht.

**Comment by jessor** [comment]
-1

Der User sollte selbst entscheiden können, ob ein Link sich im aktuellen Tab oder einem neuen Tab oder Fenster öffnet. Sobald man ein `target` setzt, kann er das nicht mehr. Deshalb bin ich dagegen, das vorzugeben. Wenn Du einen Link in einem neuen Tab öffnen möchtest, kannst Du zum Beispiel Ctrl-Click machen.

**Comment by mfuhrmann** [comment]
Macht Sinn. /close

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Daniel Kay notifications@github.com 
Datum: 13.11.2015  17:09  (GMT+01:00) 
An: "freifunk-fulda/fulda.freifunk.net" fulda.freifunk.net@noreply.github.com 
Cc: Marcel Fuhrmann fuhrmann@n3rd.org 
Betreff: Re: [fulda.freifunk.net] Mesh Karte in neuem Fenster öffnen (#18) 

Der User sollte selbst entscheiden können, ob ein Link sich im aktuellen Tab oder einem neuen Tab oder Fenster öffnet. Sobald man ein target setzt, kann er das nicht mehr. Deshalb bin ich dagegen, das vorzugeben. Wenn Du einen Link in einem neuen Tab öffnen möchtest, kannst Du zum Beispiel Ctrl-Click machen.
