### ISSUE TITLE
Firmware Link falsch

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/fulda.freifunk.net#25]
Auf der Startseite verweist der Firmware Link auf den Wiki Artikel.
Ist das so gewünscht?

**Comment by jessor** [comment]
Ich glaube nicht. Habs jetzt auf https://downloads.fulda.freifunk.net/firmware/ geändert. Danke!

**Comment by SISheogorath** [comment]
Bitte auf https://firmware.fulda.freifunk.net/stable/current/factory/ ändern

**Comment by jessor** [comment]
Done.
