### ISSUE TITLE
Firmwaredownloadseite wiederverlinken

### ISSUE THREAD

**Issue by SISheogorath** [freifunk-fulda/fulda.freifunk.net#6]
Der Link zum download der Firmware fehlt auf der neuen Webseite. 

Man könnte darüber nachdenken die Downloads auch direkt in die Seite einzubinden.

Die Variante von [Freifunk München](https://ffmuc.net/firmware/) gefällt mir recht gut.

**Comment by jessor** [comment]
Downloads sind jetzt im Footer verlinkt.

Inhalte von anderen Seiten (bzw. komplettes Wiki) direkt über die WordPress Seite abzubilden sollte wahrscheinlich separat diskutiert werden.
